config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: 'pages#home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users, only: [ :edit, :update, :show ]
  
  resources :posts do
    resources :favs, only: [:create]
    resources :uploads
  end
  resources :favs, only: [:index, :destroy]

end

app/models/fav.rb
class Fav < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :uploads, dependent: :destroy
  belongs_to :user

  has_many :favs, dependent: :destroy
  has_many :reviews, dependent: :destroy

  # CATEGORIES = ["INTERVIEW","ARTICLE", "T8PE", "VIDEO"]
  # SOUS_CATEGORIES = ["CLASH", "RAP", "LOFI", "BEATS", "TRAP", "ARTISTE", "HOW TO MAKE IT", "HOW IT'S DONE", "TUTO"]

  # validates :user_id, presence: true

  mount_uploader :photo, PhotoUploader
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  has_many :posts, dependent: :destroy
  has_many :favs, dependent: :destroy
  has_many :reviews, dependent: :destroy

  after_create :send_welcome_email

  def self.find_for_facebook_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.picture = auth.info.image
      user.token = auth.credentials.token
      user.token_expiry = Time.at(auth.credentials.expires_at)
    end
  end

  # def admin?
  #     user = user.find(params[:id])
  #     user.admin = true
  # end

  private

  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  include Pundit

  after_action :verify_authorized, except: :index, unless: :devise_controller?
  after_action :verify_policy_scoped, only: :index, unless: :devise_controller?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end
end

app/controllers/favs_controller.rb
class FavsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	skip_before_action :authenticate_user!
	skip_after_action :verify_authorized, only: :home
  	def home
  	end

  	def index
  	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: [:show, :edit, :update, :destroy]
	skip_before_action :authenticate_user!, only: [:index, :show]


	def index
		@posts = policy_scope(Post)
    end

    def show
    	@post = Post.find params[:id]
  	end

  	def new
    	@post = Post.new
    	authorize @post
  	end

  	def create
		@post = current_user.posts.build(post_params)
		authorize @post
		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def update
		@post = Post.find(params[:id])
		authorize @post
		if @post.update(post_params)
			redirect_to @post
		else
			render :edit
		end
	end

	def destroy
    	@post.destroy
    	redirect_to :posts
    	authorize @post
  	end

	private
	def set_post
		@post = Post.find(params[:id])
		authorize @post
	end
	def post_params
		params.require(:post).permit(:title, :content, :synopsis, :hashtag, :photo, :photo_cache)
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
    @user = User.find(params[:id])
    authorize @user
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favs_helper.rb
module FavsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/posts/_feature_posts.html.erb
<div class="row">
  <% @posts.each do |post| %>
    <div class="col-lg-4 rm-padding-sm col-md-6">
      <div class="card">
        <div class="card_thumb">
            <%= link_to post_path(post) do %>
              <h3 class="card_title"><%= post.title %></h3>
            <% end %>
        </div>
        <div class="card_body">
          <h4 class="card_category"><%= post.content %></h4>
          <p class="card_city"><%= post.synopsis %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/_form.html.erb
<h1>New Article</h1>  

<%= simple_form_for @post do |f| %>
<%= f.error_notification %>
  <p>
    <%= f.input :title, label: 'Le titre' %>
    <%= f.input :content, label: 'Votre article', placeholder: "Tapez ici votre article" %>
    <%= f.input :synopsis, label: 'Synopsis' %>
    <%= f.input :hashtag, label: 'Hashtag' %>
    <%= f.input :photo %>
  	<%= f.input :photo_cache, as: :hidden %>
    <%= f.submit "Publier votre article", class: "btn btn-primary text-center" %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<%= render 'feature_posts' %>

app/views/posts/new.html.erb
 <%= render 'form' %>

app/views/posts/show.html.erb
<%= cl_image_tag @post.photo, height: 300, width: 400, crop: :fill %>
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Hashtags:</strong>
  <%= @post.hashtag %>
</p>
<% if policy(@post).destroy? %>
<%= link_to 'destroy', @post, method: :delete, class:'btn btn-danger'%>
<% end %>
<% if policy(@post).edit? %>
	<%= link_to edit_post_path(@post) do %>
		<i class="glyphicon glyphicon-pencil"></i>
	<% end %>
<% end %>

<%= link_to '<- Back', posts_path %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag current_user.picture, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <% if current_user.try(:admin?) %>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Post stuff"), new_post_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= image_tag @user.picture, class:"img-circle-profile" %>

<% if @user.first_name.blank? %>
	<strong>Name</strong> : non renseigné
<% else %>
	<h3>
	<%= @user.first_name %>
	<%= @user.last_name[0].capitalize %>.
	</h3>
<% end %>

<%= @user.email %>

<% if current_user == @user %>
	<%= link_to edit_user_registration_path, class:"btn" do %>
	<%= t ".profile", default: "Modifier mon profil" %>
	<% end %>
<% end %>